byte = luajava.bindClass("byte")
short = luajava.bindClass("short")
int = luajava.bindClass("int")
long = luajava.bindClass("long")
float = luajava.bindClass("float")
double = luajava.bindClass("double")
char = luajava.bindClass("char")
boolean = luajava.bindClass("boolean")
void = luajava.bindClass("void")

byteArray = luajava.bindClass("[B")
shortArray = luajava.bindClass("[S")
intArray = luajava.bindClass("[I")
longArray = luajava.bindClass("[J")
floatArray = luajava.bindClass("[F")
doubleArray = luajava.bindClass("[D")
charArray = luajava.bindClass("[C")
booleanArray = luajava.bindClass("[Z")

String = luajava.bindClass("java.lang.String")
List = luajava.bindClass("java.util.List")
