package io.ikws4.weiju.editor;

import io.github.rosemoe.sora.widget.schemes.EditorColorScheme;

class TSEditorColorScheme extends EditorColorScheme {
    public static final int TSAnnotation = 255;
    public static final int TSAttribute = TSAnnotation + 1;
    public static final int TSBoolean = TSAttribute + 1;
    public static final int TSCharacter = TSBoolean + 1;
    public static final int TSComment = TSCharacter + 1;
    public static final int TSConditional = TSComment + 1;
    public static final int TSConstant = TSConditional + 1;
    public static final int TSConstBuiltin = TSConstant + 1;
    public static final int TSConstMacro = TSConstBuiltin + 1;
    public static final int TSConstructor = TSConstMacro + 1;
    public static final int TSError = TSConstructor + 1;
    public static final int TSException = TSError + 1;
    public static final int TSField = TSException + 1;
    public static final int TSFloat = TSField + 1;
    public static final int TSFunction = TSFloat + 1;
    public static final int TSFuncBuiltin = TSFunction + 1;
    public static final int TSFuncMarco = TSFuncBuiltin + 1;
    public static final int TSInclude = TSFuncMarco + 1;
    public static final int TSKeyword = TSInclude + 1;
    public static final int TSKeywordReturn = TSKeyword + 1;
    public static final int TSKeywordFunction = TSKeywordReturn + 1;
    public static final int TSKeywordOperator = TSKeywordFunction + 1;
    public static final int TSLabel = TSKeywordOperator + 1;
    public static final int TSMethod = TSLabel + 1;
    public static final int TSNamespace = TSMethod + 1;
    public static final int TSNone = TSNamespace + 1;
    public static final int TSNumber = TSNone + 1;
    public static final int TSOperator = TSNumber + 1;
    public static final int TSParameter = TSOperator + 1;
    public static final int TSParameterReference = TSParameter + 1;
    public static final int TSProperty = TSParameterReference + 1;
    public static final int TSPunctDelimiter = TSProperty + 1;
    public static final int TSPunctBracket = TSPunctDelimiter + 1;
    public static final int TSPunctSpecial = TSPunctBracket + 1;
    public static final int TSRepeat = TSPunctSpecial + 1;
    public static final int TSString = TSRepeat + 1;
    public static final int TSStringRegex = TSString + 1;
    public static final int TSStringEscape = TSStringRegex + 1;
    public static final int TSSymbol = TSStringEscape + 1;
    public static final int TSTag = TSSymbol + 1;
    public static final int TSTagDelimiter = TSTag + 1;
    public static final int TSText = TSTagDelimiter + 1;
    public static final int TSStrong = TSText + 1;
    public static final int TSEmphasis = TSStrong + 1;
    public static final int TSUnderline = TSEmphasis + 1;
    public static final int TSStrike = TSUnderline + 1;
    public static final int TSTitle = TSStrike + 1;
    public static final int TSLiteral = TSTitle + 1;
    public static final int TSURL = TSLiteral + 1;
    public static final int TSNote = TSURL + 1;
    public static final int TSWarning = TSNote + 1;
    public static final int TSDanger = TSWarning + 1;
    public static final int TSType = TSDanger + 1;
    public static final int TSTypeBuiltin = TSType + 1;
    public static final int TSVariable = TSTypeBuiltin + 1;
    public static final int TSVariableBuiltin = TSVariable + 1;
}
